export const genres = [
  {
    name: "аниме",
    slug: "anime",
  },
  {
    name: "биография",
    slug: "biografiya",
  },
  {
    name: "боевик",
    slug: "boevik",
  },
  {
    name: "вестерн",
    slug: "vestern",
  },
  {
    name: "военный",
    slug: "voennyy",
  },
  {
    name: "детектив",
    slug: "detektiv",
  },
  {
    name: "детский",
    slug: "detskiy",
  },
  {
    name: "для взрослых",
    slug: "dlya-vzroslyh",
  },
  {
    name: "документальный",
    slug: "dokumentalnyy",
  },
  {
    name: "драма",
    slug: "drama",
  },
  {
    name: "игра",
    slug: "igra",
  },
  {
    name: "история",
    slug: "istoriya",
  },
  {
    name: "комедия",
    slug: "komediya",
  },
  {
    name: "концерт",
    slug: "koncert",
  },
  {
    name: "короткометражка",
    slug: "korotkometrazhka",
  },
  {
    name: "криминал",
    slug: "kriminal",
  },
  {
    name: "мелодрама",
    slug: "melodrama",
  },
  {
    name: "музыка",
    slug: "muzyka",
  },
  {
    name: "мультфильм",
    slug: "multfilm",
  },
  {
    name: "мюзикл",
    slug: "myuzikl",
  },
  {
    name: "новости",
    slug: "novosti",
  },
  {
    name: "приключения",
    slug: "priklyucheniya",
  },
  {
    name: "реальное ТВ",
    slug: "realnoe-TV",
  },
  {
    name: "семейный",
    slug: "semeynyy",
  },
  {
    name: "спорт",
    slug: "sport",
  },
  {
    name: "ток-шоу",
    slug: "tok-shou",
  },
  {
    name: "триллер",
    slug: "triller",
  },
  {
    name: "ужасы",
    slug: "uzhasy",
  },
  {
    name: "фантастика",
    slug: "fantastika",
  },
  {
    name: "фильм-нуар",
    slug: "film-nuar",
  },
  {
    name: "фэнтези",
    slug: "fentezi",
  },
  {
    name: "церемония",
    slug: "ceremoniya",
  },
];

export const film = {
  status: null,
  externalId: {
    imdb: "tt0050243",
    tmdb: 554678,
    kpHD: null,
  },
  rating: {
    kp: 7.751,
    imdb: 7.7,
    filmCritics: 0,
    russianFilmCritics: 0,
    await: null,
  },
  votes: {
    kp: 355,
    imdb: 1688,
    filmCritics: 0,
    russianFilmCritics: 0,
    await: 0,
  },
  backdrop: {
    url: null,
    previewUrl: null,
  },
  movieLength: 128,
  images: {
    postersCount: 3,
    backdropsCount: 1,
    framesCount: 7,
  },
  productionCompanies: [
    {
      name: "Roy Export Company Establishment",
      url: null,
      previewUrl: null,
    },
  ],
  spokenLanguages: [
    {
      name: "English",
      nameEn: "English",
    },
  ],
  id: 2111,
  type: "movie",
  name: "Ревю Чаплина",
  description:
    "В альманах вошли 3 короткометражных фильма: «Собачья жизнь», «На плечо!», «Пилигрим».",
  distributors: {
    distributor: null,
    distributorRelease: null,
  },
  premiere: {
    world: "1959-09-01T00:00:00.000Z",
    bluray: null,
    cinema: null,
    digital: null,
    dvd: null,
    russia: null,
  },
  slogan: null,
  year: 1959,
  poster: {
    url: "https://image.openmoviedb.com/kinopoisk-images/1629390/bb8f7e4c-b92f-42be-ac45-b53a526aaa2c/600x900",
    previewUrl:
      "https://image.openmoviedb.com/kinopoisk-images/1629390/bb8f7e4c-b92f-42be-ac45-b53a526aaa2c/300x450",
  },
  facts: [],
  genres: [
    {
      name: "комедия",
    },
  ],
  countries: [
    {
      name: "Великобритания",
    },
  ],
  seasonsInfo: [],
  persons: [
    {
      id: 78810,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_78810.jpg",
      name: "Чарльз Чаплин",
      enName: "Charles Chaplin",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 220764,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_220764.jpg",
      name: "Альберт Остин",
      enName: "Albert Austin",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 218433,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_218433.jpg",
      name: "Генри Бергман",
      enName: "Henry Bergman",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 222391,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_222391.jpg",
      name: "Сид Чаплин",
      enName: "Syd Chaplin",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 207353,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_207353.jpg",
      name: "Эдна Первиэнс",
      enName: "Edna Purviance",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 115718,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_115718.jpg",
      name: "Мак Суэйн",
      enName: "Mack Swain",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 207349,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_207349.jpg",
      name: "Лойал Андервуд",
      enName: "Loyal Underwood",
      description: null,
      profession: "актеры",
      enProfession: "actor",
    },
    {
      id: 78810,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_78810.jpg",
      name: "Чарльз Чаплин",
      enName: "Charles Chaplin",
      description: null,
      profession: "композиторы",
      enProfession: "composer",
    },
    {
      id: 78810,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_78810.jpg",
      name: "Чарльз Чаплин",
      enName: "Charles Chaplin",
      description: null,
      profession: "режиссеры",
      enProfession: "director",
    },
    {
      id: 2004749,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2004749.jpg",
      name: "Пол Дэвис",
      enName: "Paul Davies",
      description: null,
      profession: "монтажеры",
      enProfession: "editor",
    },
    {
      id: 2029795,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2029795.jpg",
      name: "Дерек Парсонс",
      enName: "Derek Parsons",
      description: null,
      profession: "монтажеры",
      enProfession: "editor",
    },
    {
      id: 78810,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_78810.jpg",
      name: "Чарльз Чаплин",
      enName: "Charles Chaplin",
      description: null,
      profession: "продюсеры",
      enProfession: "producer",
    },
    {
      id: 78810,
      photo:
        "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_78810.jpg",
      name: "Чарльз Чаплин",
      enName: "Charles Chaplin",
      description: null,
      profession: "сценаристы",
      enProfession: "writer",
    },
  ],
  lists: [],
  typeNumber: 1,
  alternativeName: "The Chaplin Revue",
  enName: null,
  names: [
    {
      name: "Ревю Чаплина",
    },
    {
      name: "The Chaplin Revue",
    },
    {
      name: "A Revista de Carlitos",
      language: "BR",
      type: null,
    },
  ],
  fees: {
    world: {},
    russia: {},
    usa: {},
  },
  updatedAt: "2025-07-01T13:37:58.981Z",
  ratingMpaa: "g",
  shortDescription: null,
  technology: {
    hasImax: false,
    has3D: false,
  },
  ticketsOnSale: false,
  sequelsAndPrequels: [],
  similarMovies: [],
  imagesInfo: {
    framesCount: 7,
  },
  budget: {},
  ageRating: null,
  logo: {
    url: null,
  },
  top10: null,
  top250: null,
  deletedAt: null,
  isSeries: false,
  seriesLength: null,
  totalSeriesLength: null,
  networks: null,
  videos: {
    trailers: [],
  },
  isTmdbChecked: true,
  watchability: {
    items: [],
  },
  userRatingsParsed: true,
  keywordsParsed: false,
  studioParsed: true,
};

export const films = [
  {
    id: 8365835,
    name: null,
    alternativeName: "Spyder Games",
    type: "tv-series",
    typeNumber: 2,
    year: 2001,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: 30,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "драма",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    releaseYears: [
      {
        start: 2001,
        end: 2001,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8365836,
    name: null,
    alternativeName: "Apt. 2F",
    type: "tv-series",
    typeNumber: 2,
    year: 1997,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: 30,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "комедия",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    releaseYears: [
      {
        start: 1997,
        end: 1997,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 924778,
    name: null,
    alternativeName: "OSS 77: Operazione fior di loto",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1965,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 4.7,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 26,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 94,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "приключения",
      },
    ],
    countries: [
      {
        name: "Франция",
      },
      {
        name: "Италия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8379982,
    name: "Легендарный принц: Рождение аристократа",
    alternativeName: "Aristocratic Birth: Prince of Legend",
    type: "tv-series",
    typeNumber: 2,
    year: 2019,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: null,
    seriesLength: 22,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/10900341/a63dd161-394f-4921-949d-a597f0ee14a7/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/10900341/a63dd161-394f-4921-949d-a597f0ee14a7/300x450",
    },
    genres: [
      {
        name: "мелодрама",
      },
    ],
    countries: [
      {
        name: "Япония",
      },
    ],
    releaseYears: [
      {
        start: 2019,
        end: 2020,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8380490,
    name: "SPEC: Сага",
    alternativeName: "SICK'S - Jo no Shou",
    type: "tv-series",
    typeNumber: 2,
    year: 2018,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: null,
    seriesLength: 2,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/10809116/e01761f2-38b4-443e-a4e9-bd48c5794af8/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/10809116/e01761f2-38b4-443e-a4e9-bd48c5794af8/300x450",
    },
    genres: [
      {
        name: "детектив",
      },
      {
        name: "фэнтези",
      },
      {
        name: "комедия",
      },
    ],
    countries: [
      {
        name: "Япония",
      },
    ],
    releaseYears: [
      {
        start: 2018,
        end: 2018,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8365831,
    name: null,
    alternativeName: "Julie and Carol at Carnegie Hall",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1962,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 51,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
      {
        name: "комедия",
      },
      {
        name: "музыка",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8380903,
    name: null,
    alternativeName: "Raiders of the Stone Ring",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1968,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 25,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "короткометражка",
      },
      {
        name: "фантастика",
      },
      {
        name: "фэнтези",
      },
      {
        name: "приключения",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 674602,
    name: "Возвращайся весной",
    alternativeName: "Come Again in Spring",
    enName: null,
    type: "cartoon",
    typeNumber: 3,
    year: 2007,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 7.3,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 38,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 12,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "мультфильм",
      },
      {
        name: "короткометражка",
      },
    ],
    countries: [
      {
        name: "Канада",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8371191,
    name: null,
    alternativeName: "School-of-life",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2016,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 81,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/1898899/6b06c368-8e00-4e49-8ab1-ed2ad3543cd3/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/1898899/6b06c368-8e00-4e49-8ab1-ed2ad3543cd3/300x450",
    },
    genres: [
      {
        name: "документальный",
      },
    ],
    countries: [
      {
        name: "Аргентина",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8370939,
    name: null,
    alternativeName: "Anyaság",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1974,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 7.1,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 29,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 62,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
    ],
    countries: [
      {
        name: "Венгрия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
];

export const fav = [
  {
    id: 8380490,
    name: "SPEC: Сага",
    alternativeName: "SICK'S - Jo no Shou",
    type: "tv-series",
    typeNumber: 2,
    year: 2018,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: null,
    seriesLength: 2,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/10809116/e01761f2-38b4-443e-a4e9-bd48c5794af8/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/10809116/e01761f2-38b4-443e-a4e9-bd48c5794af8/300x450",
    },
    genres: [
      {
        name: "детектив",
      },
      {
        name: "фэнтези",
      },
      {
        name: "комедия",
      },
    ],
    countries: [
      {
        name: "Япония",
      },
    ],
    releaseYears: [
      {
        start: 2018,
        end: 2018,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8371202,
    name: "Маша по лаве шагала",
    alternativeName: null,
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2023,
    description:
      "Маше 19 лет. Она еще не понимает, что будет делать в будущем, зато уже сейчас она встречается с двумя парнями одновременно. Днем она проводит время с романтиком Васей, а по вечерам видится с брутальным Эдуардом.\nДевушке удачно удается скрывать парней друг от друга, но когда ее интригу раскрывает Вася, Маше нужно будет принять окончательное решение с кем же из двух любовников она останется в итоге.",
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 12,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 7,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: 18,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/10703959/35039383-279a-402f-9eb7-0b3df6e65072/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/10703959/35039383-279a-402f-9eb7-0b3df6e65072/300x450",
    },
    genres: [
      {
        name: "короткометражка",
      },
      {
        name: "комедия",
      },
    ],
    countries: [
      {
        name: "Россия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8385120,
    name: "Тайна затерянного острова",
    alternativeName: "Duda & Dada The Secret of HooHoo Island",
    enName: null,
    type: "cartoon",
    typeNumber: 3,
    year: 2023,
    description:
      "Маленький крот по имени Дуду просит подругу Даду о помощи и отправляется на секретный остров Хуху, чтобы отыскать маму.",
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 83,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/10592371/4cb7d695-6b25-4cb9-8451-10a823fb9373/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/10592371/4cb7d695-6b25-4cb9-8451-10a823fb9373/300x450",
    },
    genres: [
      {
        name: "мультфильм",
      },
      {
        name: "приключения",
      },
      {
        name: "детский",
      },
    ],
    countries: [
      {
        name: "Корея Южная",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8370947,
    name: null,
    alternativeName: "Killbots",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2023,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 3.8,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 171,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 46,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "ужасы",
      },
      {
        name: "фантастика",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8379982,
    name: "Легендарный принц: Рождение аристократа",
    alternativeName: "Aristocratic Birth: Prince of Legend",
    type: "tv-series",
    typeNumber: 2,
    year: 2019,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: null,
    seriesLength: 22,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/10900341/a63dd161-394f-4921-949d-a597f0ee14a7/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/10900341/a63dd161-394f-4921-949d-a597f0ee14a7/300x450",
    },
    genres: [
      {
        name: "мелодрама",
      },
    ],
    countries: [
      {
        name: "Япония",
      },
    ],
    releaseYears: [
      {
        start: 2019,
        end: 2020,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8365836,
    name: null,
    alternativeName: "Apt. 2F",
    type: "tv-series",
    typeNumber: 2,
    year: 1997,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: 30,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "комедия",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    releaseYears: [
      {
        start: 1997,
        end: 1997,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8365835,
    name: null,
    alternativeName: "Spyder Games",
    type: "tv-series",
    typeNumber: 2,
    year: 2001,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: 30,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "драма",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    releaseYears: [
      {
        start: 2001,
        end: 2001,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 924778,
    name: null,
    alternativeName: "OSS 77: Operazione fior di loto",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1965,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 4.7,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 26,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 94,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "приключения",
      },
    ],
    countries: [
      {
        name: "Франция",
      },
      {
        name: "Италия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8365831,
    name: null,
    alternativeName: "Julie and Carol at Carnegie Hall",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1962,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 51,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
      {
        name: "комедия",
      },
      {
        name: "музыка",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8380903,
    name: null,
    alternativeName: "Raiders of the Stone Ring",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1968,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 25,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "короткометражка",
      },
      {
        name: "фантастика",
      },
      {
        name: "фэнтези",
      },
      {
        name: "приключения",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 674602,
    name: "Возвращайся весной",
    alternativeName: "Come Again in Spring",
    enName: null,
    type: "cartoon",
    typeNumber: 3,
    year: 2007,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 7.3,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 38,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 12,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "мультфильм",
      },
      {
        name: "короткометражка",
      },
    ],
    countries: [
      {
        name: "Канада",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8371191,
    name: null,
    alternativeName: "School-of-life",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2016,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 81,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    poster: {
      url: "https://image.openmoviedb.com/kinopoisk-images/1898899/6b06c368-8e00-4e49-8ab1-ed2ad3543cd3/600x900",
      previewUrl:
        "https://image.openmoviedb.com/kinopoisk-images/1898899/6b06c368-8e00-4e49-8ab1-ed2ad3543cd3/300x450",
    },
    genres: [
      {
        name: "документальный",
      },
    ],
    countries: [
      {
        name: "Аргентина",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8370939,
    name: null,
    alternativeName: "Anyaság",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 1974,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 7.1,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 29,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 62,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
    ],
    countries: [
      {
        name: "Венгрия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8370940,
    name: null,
    alternativeName: "MANES",
    type: "tv-series",
    typeNumber: 2,
    year: 2023,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 6.4,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 253,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "драма",
      },
      {
        name: "комедия",
      },
    ],
    countries: [
      {
        name: "Колумбия",
      },
    ],
    releaseYears: [
      {
        start: 2023,
        end: null,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8371347,
    name: null,
    alternativeName: "You're So Cool, Brewster! The Story of Fright Night",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2016,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 8.1,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 1,
      imdb: 519,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 217,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
    ],
    countries: [
      {
        name: "Великобритания",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8365832,
    name: null,
    alternativeName: "Amour Éternel",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2016,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 52,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: 18,
    genres: [
      {
        name: "драма",
      },
      {
        name: "мелодрама",
      },
    ],
    countries: [
      {
        name: "Франция",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8371200,
    name: null,
    alternativeName: "Triumph",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2018,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 8.4,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 35,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 88,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
      {
        name: "спорт",
      },
    ],
    countries: [
      {
        name: "США",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8377629,
    name: null,
    alternativeName: "Fotos Privadas",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2020,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 6.6,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 148,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 20,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "короткометражка",
      },
      {
        name: "драма",
      },
    ],
    countries: [
      {
        name: "Бразилия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
  {
    id: 8381334,
    name: null,
    alternativeName: "Big Cats, Small World",
    type: "tv-series",
    typeNumber: 2,
    year: 2024,
    description: null,
    shortDescription: null,
    status: "completed",
    rating: {
      kp: 0,
      imdb: 7.6,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 11,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: null,
    totalSeriesLength: 96,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "документальный",
      },
    ],
    countries: [
      {
        name: "Канада",
      },
      {
        name: "Великобритания",
      },
    ],
    releaseYears: [
      {
        start: 2024,
        end: 2024,
      },
    ],
    top10: null,
    top250: null,
    isSeries: true,
    ticketsOnSale: false,
  },
  {
    id: 8381320,
    name: "Вверх ногами",
    alternativeName: "Upside Down",
    enName: null,
    type: "movie",
    typeNumber: 1,
    year: 2023,
    description: null,
    shortDescription: null,
    status: null,
    rating: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    votes: {
      kp: 0,
      imdb: 0,
      filmCritics: 0,
      russianFilmCritics: 0,
      await: 0,
    },
    movieLength: 12,
    totalSeriesLength: null,
    seriesLength: null,
    ratingMpaa: null,
    ageRating: null,
    genres: [
      {
        name: "короткометражка",
      },
    ],
    countries: [
      {
        name: "Латвия",
      },
    ],
    top10: null,
    top250: null,
    isSeries: false,
    ticketsOnSale: false,
  },
];
